# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import replication_pb2 as replication__pb2


class ReplicatorStub(object):
    """The replicator definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Replicate = channel.stream_unary(
                '/Replicator/Replicate',
                request_serializer=replication__pb2.JSONPayload.SerializeToString,
                response_deserializer=replication__pb2.Response.FromString,
                )


class ReplicatorServicer(object):
    """The replicator definition.
    """

    def Replicate(self, request_iterator, context):
        """Sends a stream of DML Operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Replicate': grpc.stream_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=replication__pb2.JSONPayload.FromString,
                    response_serializer=replication__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Replicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Replicator(object):
    """The replicator definition.
    """

    @staticmethod
    def Replicate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Replicator/Replicate',
            replication__pb2.JSONPayload.SerializeToString,
            replication__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
